name: GetRepo
inputs:
  repo:
    required: true
    type: string
    default: ${{github.repository}}
  pr_number:
    required: false
    type: number
    default: 0
  base_branch:
    required: true
    type: string
  cache_dir:
    required: false
    type: string
    default: cache
  is_cherry_pick:
    required: false
    type: boolean
    default: false
  build_script:
    required: false
    type: string
    default: ''
  github_token:
    description: 'GitHub API Access Token.'
    default: ${{ github.token }}
    required: false
  modules_blacklist:
    description: 'List of Asterisk modules to blacklist from the build'
    default: ""
    required: false

runs:
  using: "docker"
  image: "docker://ghcr.io/asterisk/asteriskci-agent-rocky8:latest"
  args:
    - entrypointGetRepo.sh
