#!/usr/bin/bash
CHECKS_DIR=$(dirname $(realpath $0))
SCRIPT_DIR=$(dirname ${CHECKS_DIR})

source ${SCRIPT_DIR}/ci.functions
source ${CHECKS_DIR}/checks.functions
set -e

assert_env_variables --print PR_DIFF_PATH || exit $EXIT_ERROR

: ${PR_CHECKLIST_PATH:=/dev/stderr}

debug_out "Checking for configure/configure.ac changes."

declare -a files=( $(sed -n -r -e "s/^diff\s+--git\s+a\/[^[:blank:]]+\s+b\/(.+)/\1/gp" ${PR_DIFF_PATH} | grep -E "(configure|configure.ac|.*m4|bootstrap.sh)$") )

if [ ${#files[@]} -eq 0 ] ; then
 	debug_out "No Autoconf related files found in commit. No checklist item needed."
	exit $EXIT_OK
fi

declare -i configure_changed=0
declare -i other_changed=0
for f in "${files[@]}" ; do
	if [[ $f =~ (configure)$ ]] ; then
		configure_changed+=1
	else 
		other_changed+=1
	fi
done

checklist_added=false
if [ $configure_changed -eq 0 ] && [ $other_changed -ne 0 ] ; then
	debug_out "${files[@]} changed manually! Adding checklist item."
	cat <<-EOF | print_checklist_item --append-newline
	- [ ] There appear to be changes to Autoconf source files (configure.ac, bootstrap.sh, *.m4) 
	but the ./configure file itself hasn't changed. If you change any Autoconf 
	source file, you must run \`./bootstrap.sh\` to regenerate the configure file.
	EOF
	checklist_added=true
fi

if [ $configure_changed -ne 0 ] && [ $other_changed -eq 0 ] ; then
	debug_out "${files[@]} changed manually! Adding checklist item."
	cat <<-EOF | print_checklist_item --append-newline
	- [ ] The ./configure file appears to have been changed manually. 
	This file is auto-generated by running \`./bootstrap.sh\` and must not 
	be modified directly. Please revert the changes to the ./configure file 
	and run \`./bootstrap.sh\` to regenerate it.
	EOF
	checklist_added=true
fi

$checklist_added && exit $EXIT_CHECKLIST_ADDED
debug_out "No issues found."
exit $EXIT_OK
