#!/usr/bin/bash

SAT_DIR=$(dirname $(readlink -fn $0))
SCRIPT_DIR=$(dirname ${SAT_DIR})

set -e
HELP=false
QUIETER=true
DRY_RUN=false

bail() {
	# Join lines that start with whitespace.
	sed -E ':a ; $!N ; s/\n\s+/ / ; ta ; P ; D' <<<"$@" >&2
	exit 1
}

print_help() {
	cat <<-EOF >/dev/stderr
	
	This script sets the security advisory versions based on a JSON document
	generated by getAdvisoryVersionsJson.sh
	
	Usage: $0 --repo=<github_org>/<github_repo> --json=<versions_json_file> --advisories=<ghsa_id>[,<ghsa_id>...] [ --dry-run ]
	
	--repo        : A GitHub org/repo 
	--json        : Must have been produced by getAdvisoryVersionsJson.sh
	--advisories  : A comma separated list of GHSA ids.
	--dry-run     : Checks the input and shows commands that would be run to set the versions 
	 
	EOF

}

source "${SCRIPT_DIR}/ci.functions"
source "${SCRIPT_DIR}/tag.functions"
source "${SAT_DIR}/sa.functions"

if [ -z "${REPO}" ] ; then
	echo -e "\nError: --repo=<github_org>/<github_repo> is required." >&2
	print_help
	exit 1
fi

if [ -z "${JSON}" ] ; then
	echo -e "\nError: --json=<versions_json_file> is required." >&2
	print_help
	exit 1
fi

if [ ! -f "${JSON}" ] ; then
	echo -e "Versions json file ${JSON} not found." >&2
	exit 1
fi

if [ -z "${ADVISORIES}" ] ; then
	echo -e "\nError: --advisories=<ghsa_id>[,<ghsa_id>...] is required." >&2
	print_help
	exit 1
fi

string_split ',' advisories "${ADVISORIES}"

fail=false
for a in "${advisories[@]}" ; do
	[[ $a =~ ^GHSA(-[0-9a-zA-Z]{4}){3}$ ]] || {
		echo "GHSA id ${a} is malformed" >&2
		fail=true
	}
done

$fail && exit 1

versions_count=$(jq '.vulnerabilities | length' "${JSON}")
if [ -z "${versions_count}" ] ; then
	echo "Unable to parse ${JSON}." >&2
	exit 1
fi	

if ! [[ "${versions_count}" =~ ^[0-9]+$ ]] || [ "${versions_count}" -le 0 ] ; then
	echo "${JSON} appears to be malformed." >&2
	exit 1
fi	

for a in "${advisories[@]}" ; do
	echo gh api -X PATCH /repos/${REPO}/security-advisories/${a} --input "${JSON}"
	${DRY_RUN} || echo gh api -X PATCH /repos/${REPO}/security-advisories/${a} --input "${JSON}"
done


