name: Releaser
inputs:
  product:
    description: |
      Product name
      (default: asterisk)
    type: string
    default: asterisk
  is_security:
    description: |
      Security?
      (Implies no RCs)
    required: true
    type: boolean
    default: false
  advisories:
    description: |
      Comma separated list of advisories.
      NO SPACES
      Example: GHSA-4xjp-22g4-9fxm,GHSA-4xjp-22g4-zzzz
    required: false
    type: string
  is_hotfix:
    description: |
      Hotfix?
      (A patch release but not security.  No RCs)
    required: true
    type: boolean
    default: false
  new_version:
    description: |
      New Version
      Examples:
        21.4.0-rc1, 21.4.0-rc2, 21.4.0, 21.4.1
        certified/21.4-cert1-rc1, certified/21.4-cert1
    required: true
    type: string
  start_version:
    description: |
      Last Version
      Only use when you KNOW that the automated
      process won't get it right.' 
    required: false
    type: string
  push_release_branches:
    description: |
      Push release branches live?
    required: true
    type: boolean
    default: false
  create_github_release:
    description: |
      Create the GitHub release?
    required: true
    type: boolean
    default: false
  push_tarballs:
    description: |
      Push tarballs to downloads server?
    required: true
    type: boolean
    default: false
  send_email:
    description: 'Send announcement emails?'
    required: true
    type: boolean
    default: false
  repo:
    type: string
    required: true
  mail_list_ga:
    type: string
    required: true
  mail_list_rc:
    type: string
    required: true
  mail_list_cert_ga:
    type: string
    required: true
  mail_list_cert_rc:
    type: string
    required: true
  mail_list_sec:
    type: string
    required: true
  sec_adv_url_base:
    type: string
    required: true
  gpg_private_key:
    type: string
    required: true
  github_token:
    type: string
    required: true
  deploy_ssh_priv_key:
    type: string
    required: true
  deploy_ssh_username:
    type: string
    required: true
  deploy_host:
    type: string
    required: true
  deploy_dir:
    type: string
    required: true

outputs:
  mail_list:
    description: 'Mailing list'
  email_announcement:
    description: 'Path to email announcement'

runs:
  using: "docker"
  image: "docker://ghcr.io/asterisk/asteriskci-agent-rocky8:latest"
  args:
    - entrypointReleaser.sh
