name: PRCheck
on:
  workflow_call:

permissions:
  actions: write
  checks: read
  contents: read
  issues: read
  pull-requests: write
  repository-projects: read
  statuses: read

env:
  REPO:            ${{ github.repository }}
  REPO_DIR:        ${{ github.workspace }}/${{ github.event.repository.name }}
  REPO_ORG:        ${{ github.event.repository.owner.login }}
  PR_NUMBER:       ${{ github.event.number }}
  BASE_BRANCH:     ${{ github.event.pull_request.base.ref }}
  WORKFLOW_NAME:   ${{ github.workflow }}
  WORKFLOW_RUN_ID: ${{ github.run_id }}
  GH_TOKEN:        ${{ secrets.GITHUB_TOKEN }}
  LOG_DIR:         ${{ github.workspace }}/logs
  LOG_FILE:        ${{ github.workspace }}/logs/job_summary.txt
  BUILD_CACHE_KEY: ${{ github.workflow }}-${{ github.run_number }}-${{ github.event.number }}-${{ github.event.pull_request.base.ref }}
  TRIGGER:         ${{ github.event.action }}
  TESTING_IN_PROGRESS: ${{ vars.PR_SUBMIT_TESTING_IN_PROGRESS }}
  TESTS_PASSED:        ${{ vars.PR_SUBMIT_TESTS_PASSED }}
  TESTS_FAILED:        ${{ vars.PR_SUBMIT_TESTS_FAILED }}
  RECHECKPR_LABEL:            ${{ vars.RECHECKPR_LABEL }}
  TESTSUITE_REPO:             ${{ vars.TESTSUITE_REPO }}
  PR_STATE_CHANGE_DELAY_SEC:  ${{ vars.PR_STATE_CHANGE_DELAY_SEC || 120 }}
  ASSOCIATED_TEST_PR_REGEX:   ${{ vars.ASSOCIATED_TEST_PR_REGEX }}
  CHERRY_PICK_VALID_BRANCHES: ${{ vars.CHERRY_PICK_VALID_BRANCHES }}
  SECURITY_FIX_BRANCHES:      ${{ vars.SECURITY_FIX_BRANCHES }}
  TEST_TYPE:                  check

jobs:
  Setup:
    runs-on: ubuntu-latest
    outputs:
      testsuite_test_pr: ${{ steps.setup.outputs.ASSOCIATED_TEST_PR }}
      test_type:         ${{ steps.setup.outputs.TEST_TYPE }}
    steps:
        # ACTIONS_PATH, SCRIPT_DIR, NORMALIZED_BRANCH env vars
      - name: GetActionsRepo
        uses: asterisk/asterisk-ci-actions/GetActionsRepo@main

      - id: setup
        name: Setup
        run: |
          # Setup
          echo "TEST_TYPE=${TEST_TYPE}" >> "${GITHUB_OUTPUT}"
          if [ "$TRIGGER" != "labeled" ] ; then
            # Wait then get testsuite PR
            echo "Waiting for ${PR_STATE_CHANGE_DELAY_SEC} seconds to give user a chance to add PR comments"
            sleep ${PR_STATE_CHANGE_DELAY_SEC}
          fi

          echo "Labeling"
          gh pr edit --repo ${REPO} \
            --remove-label ${RECHECKPR_LABEL} \
            --remove-label ${TESTS_PASSED} \
            --remove-label ${TESTS_FAILED} \
            --add-label ${TESTING_IN_PROGRESS} \
            ${PR_NUMBER} || :

          # Testsuite PR will be placed in ASSOCIATED_TEST_PR in both
          # GITHUB_ENV and GITHUB_OUTPUT by the script.
          ${SCRIPT_DIR}/getAssociatedTestPR.sh \
            --repo=${REPO} \
            --pr-number=${PR_NUMBER} \
            --associated-test-pr-regex="${ASSOCIATED_TEST_PR_REGEX}"

          echo "Attempting to delete any existing cache"
          gh cache delete -R ${REPO} ${BUILD_CACHE_KEY} || :

  Test:
    name: Test
    needs: [ Setup ]
    permissions:
      actions: read
      checks: read
      contents: read
      issues: read
      pull-requests: read
      statuses: read
    uses: ./.github/workflows/AsteriskUnitGateTest.yml
    with:
      test_type:         ${{ needs.Setup.outputs.test_type }}
      asterisk_repo:     ${{ github.repository }}
      pr_number:         ${{ github.event.number }}
      base_branch:       ${{ github.event.pull_request.base.ref }}
      is_cherry_pick:    false
      build_options:     ${{ vars.BUILD_OPTIONS }}
      unittest_command:  ${{ vars.UNITTEST_COMMAND }}
      testsuite_repo:    ${{ vars.TESTSUITE_REPO }}
      testsuite_test_pr: ${{ needs.Setup.outputs.testsuite_test_pr }}
      gatetest_list:     ${{ vars.GATETEST_LIST }}
      gatetest_commands: ${{ vars.GATETEST_COMMANDS }}
      sipp_version:      ${{ vars.SIPP_VERSION }}

  PostWorkflow:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: [Setup,Test]
    env:
      RESULT_SETUP:   ${{ needs.Setup.result }}
      RESULT_CHECK:   ${{ needs.Test.result }}
    steps:
        # ACTIONS_PATH, SCRIPT_DIR, NORMALIZED_BRANCH env vars
      - name: GetActionsRepo
        uses: asterisk/asterisk-ci-actions/GetActionsRepo@main

      - name: Check status
        shell: bash
        run: |

          label=""
          RESULT=$RESULT_CHECK
          echo "Setup status: $RESULT_SETUP Check status: $RESULT_CHECK"
          case $RESULT_CHECK in
            success)
              label=$TESTS_PASSED
              gh cache delete -R ${REPO} ${BUILD_CACHE_KEY} || :
              ;;
            failure)
              label=$TESTS_FAILED
              ;;
            cancelled)
              gh cache delete -R ${REPO} ${BUILD_CACHE_KEY} || :
              ;;
            skipped)
              if [ "$RESULT_SETUP" == "failure" ] ; then
                  RESULT=failure
                  label=$TESTS_FAILED
              fi
              ;;
            *)
              ;;
          esac

          echo "RESULT: '${RESULT}'  Setting label: '$label'"
          gh pr edit --repo ${REPO} \
            --remove-label ${TESTING_IN_PROGRESS} \
            ${label:+--add-label $label} \
              $PR_NUMBER || :

          if [[ $RESULT =~ (success|failure) ]] ; then
            if [[ "${REPO}" =~ GHSA ]] ; then
              CPVB=${SECURITY_FIX_BRANCHES}
            else
              CPVB=${CHERRY_PICK_VALID_BRANCHES}
            fi
            ${SCRIPT_DIR}/PRChecks/addPRChecklistIfNeeded.sh \
              --repo=${REPO} \
              --pr-number=${PR_NUMBER} \
              --cherry-pick-valid-branches=${CPVB}

            shopt -s extglob
            gh api --paginate /repos/${REPO}/actions/runs/${GITHUB_RUN_ID}/jobs > /tmp/jobs.json || :
            jobname=$(jq -r '.jobs[]| select(.name | contains("PostWorkflow")) | .name' /tmp/jobs.json 2>/dev/null || :)
            # Action / CPCheck / PostWorkflow
            jobname="${jobname////}"
            # Action CPCheck PostWorkflow
            jobname="${jobname//?(Action|PostWorkflow)/}"
            # '  CPCheck  '
            jobname="${jobname// /}"
            ${SCRIPT_DIR}/createJobSummary.sh \
              --result=${RESULT} \
              --repo=${REPO} \
              --workflow-name="${jobname}" \
              --pr-number=${PR_NUMBER} \
              --workflow-run=${WORKFLOW_RUN_ID} \
              --tmp-dir=./run-${WORKFLOW_RUN_ID} \
              --job-summary-output=job_summary.txt \
              --artifact-suffix="-${TEST_TYPE}-${GITHUB_RUN_NUMBER}" \
              --write-step-summary \
              --add-pr-comment \
              --verbose || :
          fi
          exit 0
